### ISSUE TITLE
Import error on populus compile

### ISSUE THREAD

**Issue by Neflux** [algorithmiaio/danku#14]
pupulus compile output:
```
Traceback (most recent call last):
  File "/home/talos/tirocinio/danku/venv/bin/populus", line 7, in <module>
    from populus.cli import main
  File "/home/talos/tirocinio/danku/venv/lib/python3.6/site-packages/populus/__init__.py", line 24, in <module>
    from .project import Project  # NOQA
  File "/home/talos/tirocinio/danku/venv/lib/python3.6/site-packages/populus/project.py", line 10, in <module>
    from populus.config.defaults import (
  File "/home/talos/tirocinio/danku/venv/lib/python3.6/site-packages/populus/config/__init__.py", line 1, in <module>
    from .base import (  # noqa: F401
  File "/home/talos/tirocinio/danku/venv/lib/python3.6/site-packages/populus/config/base.py", line 12, in <module>
    from populus.utils.mappings import (
  File "/home/talos/tirocinio/danku/venv/lib/python3.6/site-packages/populus/utils/mappings.py", line 8, in <module>
    from eth_utils import (
ImportError: cannot import name 'force_text'
```
How can I fix this? What versions should I have of populus, eth-utils, rlp that don't conflict with each other?

**Comment by besirkurtulmus** [comment]
Duplicate issue at: #4 

Closing this one.
