### ISSUE TITLE
got an error when processing  `python -W ignore competition/download_train_visualize.py`

### ISSUE THREAD

**Issue by hammeWang** [algorithmiaio/danku#5]
Connecting to geth...

Connected to the geth node!

Downloading training data from the contract...

Traceback (most recent call last):
  File "/Users/hammer/andlinks/danku/venv/lib/python3.6/site-packages/web3/contract.py", line 844, in call_contract_function
    output_data = decode_abi(output_types, return_data)
  File "/Users/hammer/andlinks/danku/venv/lib/python3.6/site-packages/eth_abi/abi.py", line 109, in decode_abi
    return decoder(stream)
  File "/Users/hammer/andlinks/danku/venv/lib/python3.6/site-packages/eth_abi/decoding.py", line 102, in __call__
    return self.decode(stream)
  File "/Users/hammer/andlinks/danku/venv/lib/python3.6/site-packages/eth_utils/functional.py", line 22, in inner
    return callback(fn(*args, **kwargs))
  File "/Users/hammer/andlinks/danku/venv/lib/python3.6/site-packages/eth_abi/decoding.py", line 140, in decode
    yield decoder(stream)
  File "/Users/hammer/andlinks/danku/venv/lib/python3.6/site-packages/eth_abi/decoding.py", line 102, in __call__
    return self.decode(stream)
  File "/Users/hammer/andlinks/danku/venv/lib/python3.6/site-packages/eth_abi/decoding.py", line 165, in decode
    raw_data = cls.read_data_from_stream(stream)
  File "/Users/hammer/andlinks/danku/venv/lib/python3.6/site-packages/eth_abi/decoding.py", line 247, in read_data_from_stream
    len(data),
eth_abi.exceptions.InsufficientDataBytes: Tried to read 32 bytes.  Only got 0 bytes

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "competition/download_train_visualize.py", line 29, in <module>
    contract_train_data_length = danku.call().get_train_data_length()
  File "/Users/hammer/andlinks/danku/venv/lib/python3.6/site-packages/web3/contract.py", line 866, in call_contract_function
    raise_from(BadFunctionCallOutput(msg), e)
  File "/Users/hammer/andlinks/danku/venv/lib/python3.6/site-packages/web3/utils/exception_py3.py", line 2, in raise_from
    raise my_exception from other_exception
web3.exceptions.BadFunctionCallOutput: Could not transact with/call contract function, is contract deployed correctly and chain synced?

**Comment by besirkurtulmus** [comment]
@hammeWang: Do you have `geth` up and running?

**Comment by smalldog3** [comment]
Hello @hammeWang , did you solve this question? Any advice?

**Comment by hammeWang** [comment]
@besirkurtulmus yep

**Comment by hammeWang** [comment]
@besirkurtulmus and today I got another error:
` File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)`

**Comment by smalldog3** [comment]
@hammeWang 
Hello, how did you solve your first error? Would you provide some specific advice? Thank you

**Comment by besirkurtulmus** [comment]
@hammeWang Can you give the full traceback?

**Comment by besirkurtulmus** [comment]
@smalldog3 Do you have `geth` up and running?

**Comment by smalldog3** [comment]
@besirkurtulmus 
Hello, Thank you for response. Do you mean the chain should be fully synced?

**Comment by smalldog3** [comment]
@besirkurtulmus  I just used light node and fixed this error. Thank you!

**Comment by besirkurtulmus** [comment]
@smalldog3 Yeah, the error says that the transaction didn't go through, and asks you if your chain (aka. the blockchain is in sync).

Glad that it worked. Were you running a full-node beforehand?

**Comment by smalldog3** [comment]
@besirkurtulmus No, I did not run the full-node.
Besides, I find a new question:
![image](https://user-images.githubusercontent.com/31265790/37855473-d08c9d04-2ec5-11e8-8cc8-68971715bef6.png)
I can not execute it. Do I need to buy ether before executing it?

**Comment by besirkurtulmus** [comment]
@smalldog3 Can you ask that under a new issue? Thanks.

**Comment by besirkurtulmus** [comment]
Closing issue since it's solved.
